config/routes.rb
RentCar::Application.routes.draw do

  root :to => "clientes#index"
  resources :carros
  resources :clientes
  resources :locacoes
  

end

app/models/carro.rb
class Carro < ActiveRecord::Base
  has_many :locacoes
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  has_many :locacoes
end

app/models/locacao.rb
class Locacao < ActiveRecord::Base
  belongs_to :carro
  belongs_to :cliente
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carros_controller.rb
class CarrosController < ApplicationController
  # GET /carros
  # GET /carros.xml
  def index
    @carros = Carro.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @carros }
    end
  end

  # GET /carros/1
  # GET /carros/1.xml
  def show
    @carro = Carro.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @carro }
    end
  end

  # GET /carros/new
  # GET /carros/new.xml
  def new
    @carro = Carro.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @carro }
    end
  end

  # GET /carros/1/edit
  def edit
    @carro = Carro.find(params[:id])
  end

  # POST /carros
  # POST /carros.xml
  def create
    @carro = Carro.new(params[:carro])

    respond_to do |format|
      if @carro.save
        format.html { redirect_to(@carro, :notice => 'Carro criado com sucesso.') }
        format.xml  { render :xml => @carro, :status => :created, :location => @carro }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @carro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /carros/1
  # PUT /carros/1.xml
  def update
    @carro = Carro.find(params[:id])

    respond_to do |format|
      if @carro.update_attributes(params[:carro])
        format.html { redirect_to(@carro, :notice => 'Carro atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @carro.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /carros/1
  # DELETE /carros/1.xml
  def destroy
    @carro = Carro.find(params[:id])
    @carro.destroy

    respond_to do |format|
      format.html { redirect_to(carros_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to(@cliente, :notice => 'Cliente cadastrado com sucesso.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente atualizado com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/locacoes_controller.rb
# encoding: utf-8
class LocacoesController < ApplicationController
  def index
    query = Locacao.scoped
    
    cliente = "#{params[:cliente]}"
    carro = "#{params[:carro]}"
    
    query = query.where(:cliente_id => cliente) unless cliente.blank?
    query = query.where(:carro_id => carro) unless carro.blank?
    query = query.where('data_locacao LIKE ?', "#{params[:data_locacao]}%") unless params[:data_locacao].blank?
    query = query.where('data_entrega LIKE ?', "#{params[:data_entrega]}%") unless params[:data_entrega].blank?
    query = query.where('valor LIKE ?', "#{params[:valor]}%") unless params[:valor].blank?
    
    @locacoes = query.all
    

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locacoes }
    end
  end

  def new
    @locacao = Locacao.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @locacao }
    end
  end
  
  def edit
    @locacao = Locacao.find(params[:id])
  end
  
  def destroy
    @locacao = Locacao.find(params[:id])
    @locacao.destroy

    respond_to do |format|
      format.html { redirect_to(locacoes_url) }
      format.xml  { head :ok }
    end
  end
  
  def show
    @locacao = Locacao.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @locacao }
    end
  end
  
  def create
    @locacao = Locacao.new(params[:locacao])

    respond_to do |format|
      if @locacao.save
        format.html { redirect_to(@locacao, :notice => 'Locacao realizada com sucesso.') }
        format.xml  { render :xml => @locacao, :status => :created, :location => @locacao }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @locacao.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @locacao = Locacao.find(params[:id])

    respond_to do |format|
      if @locacao.update_attributes(params[:locacao])
        format.html { redirect_to(@locacao, :notice => 'Locação atualizada com sucesso.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @locacao.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carros_helper.rb
module CarrosHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/locacoes_helper.rb
module LocacoesHelper

  def select_clientes(attr_name, options={}, html_options={})
    select_options = options_from_collection_for_select(Cliente.all, 'id', 'nome', options[:selected])
    
    if options.key?(:form)
      options[:form].select attr_name, select_options, html_options
    else
      select_tag attr_name, select_options, html_options
    end
  end
  
  def select_carros(attr_name, options={}, html_options={})
    select_options = options_from_collection_for_select(Carro.all, 'id', 'marca', options[:selected])
    
    if options.key?(:form)
      options[:form].select attr_name, select_options, html_options
    else
      select_tag attr_name, select_options, html_options
    end
  end
end

app/views/carros/_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif" style="text-align:center;"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
	<div id="CONTEUDO">
	<%= form_for(@carro) do |f| %>
  	<% if @carro.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@carro.errors.count, "error") %> prohibited this carro from being saved:</h2>

	      <ul>
	      <% @carro.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
  	<% end %>

	 <table>
		 <tr> <td> <h3> Dados do Carro: </h3> </td></tr>
		 
		<tr> 
		   <td> <%= f.label :marca %> </td> <td> <%= f.text_field :marca %> </td> 
		   
		 </tr>
		<tr> 
		   <td> <%= f.label :modelo %> </td> <td> <%= f.text_field :modelo %> </td> 
		   
		 </tr>
		 <tr>
		    <td> <%= f.label :ano %> </td> <td> <%= f.text_field :ano %> </td>
		 </tr>
		 <tr>
		 	<td><%= f.label :placa %></td> <td><%= f.text_field :placa %></td>
		 </tr>
		 <tr>
		 	<td><%= f.label :cor %></td> <td><%= f.text_field :cor %></td>
		 </tr>
		 <tr>
			 <td> <%= f.label :ano_aquisicao %></td> <td> <%= f.text_field :ano_aquisicao %> </td>
		 </tr>
		 
		 <tr> <td> <%= f.submit %> </td> <td><%= link_to 'Voltar para listagem', carros_path %></td> </tr>
	</table>
  </div>

<% end %>

 </div>

</body>
</html>

app/views/carros/index.html.erb
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
   <div id="CONTEUDO">
	<b> Listagem de Carros</b>
	<span id=linknew> <%= link_to 'Novo Carro', new_carro_path%> </span>
	<hr>
	<table width="300" class="mytable">
		<tr>
    		<th width=20%>Marca</th>
    		<th>Modelo</th>
    		<th>Ano</th>
    		<th>Placa</th>
    		<th width=10%>Ano aquisicao</th>
    		<th>Cor</th>
    		<th colspan=2> Ações </th>
  		</tr>
  <% @carros.each do |carro| %>
  <tr>
    <td><%= carro.marca %></td>
    <td><%= carro.modelo %></td>
    <td><%= carro.ano %></td>
    <td><%= carro.placa %></td>
    <td><%= carro.ano_aquisicao %></td>
    <td><%= carro.cor %></td>
    <td style="padding: 5px; width: 20px; height: 20px;"><%= link_to 'E', edit_carro_path(carro), :title => 'Editar' %></td>
    <td style="padding: 5px; width: 20px; height: 20px;"><%= link_to 'R', carro, :confirm => 'Tem certeza que deseja remover este carro?', :method => :delete, :title => 'Remover' %></td>
  </tr>
  <% end %>
        </table>
		 
		
    </div>
 
   
  
 </div>

</body>
</html>

app/views/carros/new.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
   <div id="CONTEUDO">
	<%= form_for(@carro) do |f| %>
          <b> Cadastro de Carros</b>
		   
		  <hr>
		 
	 <table>
		 <tr> <td> <h3> Dados do Carro: </h3> </td></tr>
		 
		<tr> 
		   <td> <%= f.label :marca %> </td> <td> <%= f.text_field :marca %> </td> 
		   
		 </tr>
		<tr> 
		   <td> <%= f.label :modelo %> </td> <td> <%= f.text_field :modelo %> </td> 
		   
		 </tr>
		 <tr>
		    <td> <%= f.label :ano %> </td> <td> <%= f.text_field :ano, :size=>3 %> </td>
		 </tr>
		 <tr>
		 	<td><%= f.label :placa %></td> <td><%= f.text_field :placa, :size=>6 %></td>
		 </tr>
		 <tr>
		 	<td><%= f.label :cor %></td> <td><%= f.text_field :cor, :size=>6 %></td>
		 </tr>
		 <tr>
			 <td> <%= f.label :ano_aquisicao, 'Ano Aqusição' %></td> <td> <%= f.text_field :ano_aquisicao, :size=>3 %> </td>
		 </tr>
		 
		 <tr> <td class="link_voltar"> <%= f.submit %> </td> <td><%= link_to 'Voltar para listagem', carros_path %></td> </tr>
	</table>
	<% end %>
    </div>
 
   
  
 </div>

</body>
</html>

app/views/carros/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="#"> Locações</a>
		</div>
	<div id="CONTEUDO">
	<%= form_for(@carro) do |f| %>

	 <table>
		<p id="notice"><%= notice %></p>
			<hr>
		<p>
  		<b>Marca:</b>
  		<%= @carro.marca %>
		</p>

		<p>
  		<b>Modelo:</b>
  		<%= @carro.modelo %>
		</p>

		<p>
  		<b>Ano:</b>
  		<%= @carro.ano %>
		</p>

		<p>
  		<b>Placa:</b>
  		<%= @carro.placa %>
		</p>

		<p>
  		<b>Ano aquisicao:</b>
  		<%= @carro.ano_aquisicao %>
		</p>

		<p>
  		<b>Cor:</b>
  		<%= @carro.cor %>
		</p>

		<span id="links">
 	 		 <%= link_to 'Editar', edit_carro_path(@carro) %>
 	 		 	 |
	 		<%= link_to 'OK', carros_path %>
		</span>
	</table>
  </div>
  
<% end %>

 </div>

</body>
</html>

app/views/clientes/_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
   <div id="CONTEUDO">
   	<%= form_for(@cliente) do |f| %>
          <b> Cadastro de Clientes</b>
		   
		  <hr> 
		 
		 <table>
		 <tr> <td> <h3> Dados Pessoais: </h3> </td></tr>
		 <tr> 
		   <td> <%= f.label :nome %> </td> <td> <%= f.text_field :nome, :size=>50%> </td> 
    		
		 </tr>
		<tr> 
		  <td> <%= f.label :nome_pai, 'Nome do Pai'%> </td> <td> <%= f.text_field :nome_pai, :size=>50%> </td> 
		   
		 </tr>
		 <tr>
			<td> <%= f.label :nome_mae,'Nome da Mãe'%> </td> <td> <%= f.text_field :nome_mae, :size=>50%> </td> 
		 </tr>
		 <tr>
		 <td> <%= f.label :data_nascimento, 'Data de Nascimento '%> </td> <td> <%= f.text_field :data_nascimento, :size=>12%> <%= f.label :telefone%> <%= f.text_field :telefone, :size=>12%></td>
		 </tr>
		 <tr>
		    <td>  <%= f.label :cpf, 'CPF'%> </td> <td>  <%= f.text_field :cpf, :size=>12%>  <%= f.label :habilitacao, 'Habilitação'%>  <%= f.text_field :habilitacao, :size=>12%></td>
			
		 </tr>
		 
		 <tr>
		    <td>  <%= f.label :naturalidade%> </td> <td>  <%= f.text_field :naturalidade, :size=>12%> </td>
		 </tr>
		 
		<tr> <td> <h3> Endereço: </h3> </td></tr>
		<tr> 
		   <td>  <%= f.label :logradouro%> </td> <td>  <%= f.text_field :logradouro, :size=>50%> </td> 
		   
		 </tr>
		<tr> 
		   <td> <%= f.label :numero, 'Número'%> </td> <td>  <%= f.text_field:numero, :size=>4%>   <%= f.label :cep, 'CEP'%> <%= f.text_field :cep,  :size=>10%> </td> 
		 <tr>
		    <td> <%= f.label :bairro%> </td> <td> <%= f.text_field :bairro, :size=>20%> </td>
		 </tr>
		 <tr>
		 <td> <%= f.label :municipio, 'Município'%></td> <td> <%= f.text_field :municipio, :size=>20%></td>
		 </tr>
		 <tr>
		   <td> <%= f.label :estado%> </td> <td> <%= f.text_field :estado, :size=>12%> </td>
		 </tr>
		 <tr>
		    <td> <%= f.label :naturalidade%> </td> <td> <%= f.text_field:naturalidade, :size=>12%> </td>
		 </tr>
		 
		 <tr> <td id='novo'> <%= f.submit %> </td> <td><%= link_to 'Voltar para listagem', clientes_path %></td> </tr>
		 </table>
	<% end %>
    </div>
 
   
  
 </div>

</body>
</html>

app/views/clientes/index.html.erb
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
   <div id="CONTEUDO">
          <b> Listagem de Clientes</b>
          <span id=linknew> <%= link_to 'Novo Cliente', new_cliente_path%> </span>
		   <hr>
		   <table width="300" class="mytable">
		    <tr>
              <th width=15%>Nome</th>
              <th>Nascimento</th>
              <th width=15%>CPF</th>
              <th>Habilitacao</th>
              <th>Telefone</th>
              <th>Logradouro</th>
              <th>Numero</th>
              <th>Bairro</th>
              <th>Municipio</th>
              <th>Estado</th>
              <th colspan=2 >Ações</th>
            </tr>
	<% @clientes.each do |cliente| %>
	<tr>
    <td><%= cliente.nome %></td>
    <td><%= cliente.data_nascimento %></td>
    <td><%= cliente.cpf %></td>
	<td><%= cliente.habilitacao %></td>
    <td><%= cliente.telefone %></td>
	<td><%= cliente.logradouro %></td>
    <td><%= cliente.numero %></td>
    <td><%= cliente.bairro %></td>
    <td><%= cliente.municipio %></td>
    <td><%= cliente.estado %></td>
    <td><%= link_to 'E', edit_cliente_path(cliente), :title => 'Editar' %></td>
    <td><%= link_to 'R', cliente, :confirm => "Tem certeza que deseja remover o cliente #{cliente.try(:nome)}?", :method => :delete, :title => 'Remover' %></td>
  </tr>
  <% end %>
    </table>
		 
		
    </div>
 
   
  
 </div>

</body>
</html>

app/views/clientes/new.html.erb
<%= render 'form' %>

app/views/clientes/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
	<div id="CONTEUDO">
	<%= form_for(@cliente) do |f| %>

	 <table>
		<p id="notice"><%= notice %></p>
			<hr>
		<p>
		 <b>Nome:</b>
			  <%= @cliente.nome %>
   		 </p>

		<p>
  		<b>Nome pai:</b>
	  		 <%= @cliente.nome_pai %>
		</p>

		<p>
	   	<b>Nome mãe:</b>
  			<%= @cliente.nome_mae %>
		</p>

		<p>
  		<b>Data nascimento:</b>
  			<%= @cliente.data_nascimento %>
		</p>

		<p>
  		<b>Telefone:</b>
  			<%= @cliente.telefone %>
		</p>

		<p>
  		<b>Cpf:</b>
  			<%= @cliente.cpf %>
		</p>
			
		<p>
  		<b>Habilitação:</b>
  			<%= @cliente.habilitacao %>
		</p>
		
		<p>
  		<b>Naturalidade:</b>
		  	<%= @cliente.naturalidade %>
		</p>
		
		<p>
  		<b>Logradouro:</b>
  			<%= @cliente.logradouro %>
		</p>
	
		<p>
  		<b>Número:</b>
  			<%= @cliente.numero %>
		</p>
		
		<p>
  		<b>Bairro:</b>
  			<%= @cliente.bairro %>
		</p>
		
		<p>
  		<b>Município:</b>
  			<%= @cliente.municipio %>
		</p>
		
		<p>
  		<b>Cep:</b>
  			<%= @cliente.cep %>
		</p>
		
		<p>
  		<b>Estado:</b>
  	  		<%= @cliente.estado %>
		</p>
		
		<div id="links">
			<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
			<%= link_to 'OK', clientes_path %>
		</div>
	</table>
  </div>
  
<% end %>

 </div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentCar</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locacoes/_form.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
   <div id="CONTEUDO">
   	<%= form_for(@locacao) do |f| %>
          <b> Cadastro de Locação</b>
		   
		  <hr> 
		 
		 <table>
		 <tr> <td> <h3> Dados da Locação: </h3> </td></tr>
		 <tr> 
		   <td><%= f.label :cliente, 'Cliente'%> <%= f.select :cliente_id, options_from_collection_for_select(Cliente.all, 'id', 'nome', @locacao.cliente_id), :include_blank => true %></td>
		   
 		   <td><%= f.label :carro, 'Carro'%> <%= f.select :carro_id, options_from_collection_for_select(Carro.all, 'id', 'marca', @locacao.carro_id), :include_blank => true%></td>
 		   
 		   <tr>
 		    <td><%= f.label :data_locacao, 'Data de Locação'%></td><td> <%= f.text_field :data_locacao, :size=>9 %></td></tr>
 		   
        <tr>
 		      <td><%= f.label :data_entrega, 'Data de Entrega'%></td><td> <%= f.text_field :data_entrega, :size=>9 %></td></tr>
 		   
 		   <tr><td><%= f.label :valor, 'Valor'%></td><td> <%= f.text_field :valor, :size=>9 %></td></tr> 
    		
		 <tr> <td id='novo'> <%= f.submit %> </td> <td><%= link_to 'Voltar para listagem', locacoes_path %></td> </tr>
		 </table>
	<% end %>
    </div>
 
   
  
 </div>

</body>
</html>

app/views/locacoes/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<link href="estilo.css" rel="stylesheet" type="text/css">
<meta content="text/html; charset=ISO-8859-1" http-equiv="content-type">
<title>Ret-Car - Locação de veículos</title>
</meta></head>
<body>

<div id="GERAL">

   <div id="TOPO" style="text-align:center;"> 
        <img src="/images/logo_01.gif"> </img> 
   </div>
      <div id="MENU"> 
		    <a href="/carros"> Carros</a> 
			<a href="/clientes"> Clientes</a> 
			<a href="/locacoes"> Locações</a>
		</div>
	<div id="CONTEUDO">
	<%= form_for(@locacao) do |f| %>

	 <table>
		<p id="notice"><%= notice %></p>
			<hr>
		<p>
		 <b>Nome do Cliente:</b>
			  <%= @locacao.cliente.try(:nome) %>
   		 </p>

		<p>
  		<b>Marca do Carro:</b>
	  		 <%= @locacao.carro.try(:marca) %>
		</p>

		<p>
	   	<b>Data de Locação:</b>
  			<%= @locacao.data_locacao %>
		</p>

		<p>
  		<b>Data de Entrega:</b>
  			<%= @locacao.data_entrega %>
		</p>

		<p>
  		<b>Valor:</b>
  			<%= @locacao.valor %>
		</p>
		
		<div id="links">
			<%= link_to 'Edit', edit_locacao_path(@locacao) %> |
			<%= link_to 'OK', locacoes_path %>
		</div>
	</table>
  </div>
  
<% end %>

 </div>

</body>
</html>